services:
  app:
    build: .
    container_name: hello-app
    env_file:
      - .env
    environment:
      DB_HOST: host.docker.internal
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --use-colors
    extra_hosts:
      - "host.docker.internal:host-gateway"
